# I. Modélisation 
## 1) Présentation du cadre
Considérons un graphe orienté $G = (S, A)$, où $S$ est un ensemble et $A \subset S^2$. Il y a une flèche du sommet $i \in S$ vers le sommet $j \in S$ si $(i, j) \in A$. Dans notre cas, les flèches représentent les routes et les sommets les points d'intersection. Pour tout couple $(i, j) \in S^2$, notons $P_{i,j}$ l'ensemble des chemins simples de $i$ vers $j$, c'est-à-dire les suites injectives de sommets adjacents débutant par $i$ et s'achevant par $j$. Pour simplifier les notations, supposons que $S = [|1, n|]$ où $n = |S|$. \
Pour tout couple $(i, j) \in S^2$, notons $q_{i, j}$ la demande du sommet i vers le sommet j, autrement dit le nombre de voyageurs ayant pour origine $i$ et pour destination $j$ durant la période d'analyse.
La matrice $Q = (q_{i,j})_{1 \leq i, j \leq n}$ est appelée matrice d'origine-destination (OD).
Soit $a \in A$. Nous supposons que le temps de trajet de $a$, $t_a$, est uniquement fonction du flux sur $a$, $x_a$, c'est-à-dire le nombre de voyageurs passant par $a$. Pour tout couple $(i, j) \in S^2$ et tout chemin $k \in P_{i, j}$ les reliant, notons $f_k^{i,j}$ et $c_k^{i,j}$ les flux et temps de trajet, respectivement, du chemin $k$, en comptabilisant uniquement les voyageurs allant de $i$ à $j$ ; et pour tout $a \in A$, posons $\delta^{i,j}_{a,k} = 1$ si l'arête $a$ fait partie du chemin $k$ et $0$ sinon.
Nous avons alors les relations suivantes :
$$\forall (i, j) \in S^2, \forall k \in P_{i, j}, \, c_k^{i, j} = \sum_{a \in A} \delta^{i,j}_{a,k}t_a(x_a)$$
$$\forall a \in A, x_a = \sum_{(i, j) \in S^2}\sum_{a\in A}\delta^{i,j}_{a,k}f_k^{i,j}$$
$$\forall (i, j) \in S^2, q_{i, j} = \sum_{k \in P_{i, j}}f_{k}^{i, j}$$
La première exprime que le temps de trajet sur un certain chemin est la somme des temps de trajets sur les arêtes qu'il comprend, la deuxième que le flux sur une arête est la somme des flux sur tous les chemins qui passent à travers cet arc et la troisième que la demande d'un couple origine-demande est égale à la somme des flux sur les chemins les reliant.
Dans les différentes solutions du modèle que nous aborderons, les variables endogènes seront $f_k^{i,j}$ (et donc $x_a$), $Q$ est exogène.

## 2) Equilibres
L'optimum système est une configuration des flux minimisant la somme des temps de trajets des voyageurs. Il s'agit donc d'une solution au programme

\begin{align*}
&\min \sum_{a \in A} x_a t_a(x_a) \\
\text{s.c.} \quad & \\
& \forall (i, j) \in S^2, q_{i, j} = \sum_{k \in P_{i, j}}f_{k}^{i, j} \\
& \forall (i, j) \in S^2, \forall k \in P_{i, j}, f_{k}^{i, j} \geq 0 \\
\end{align*}

L'équilibre de Nash est moins immédiat à formuler. Informellement, dans cette situation, aucune déviation unilatérale n'est profitable pour l'agent qui la réalise (en considérant des agents infinitésimaux). Autrement dit, pour tout couple origine-destination $(i, j)$ et tout chemin $k \in P_{i, j}$ qui est emprunté (c'est-à-dire $f_{k}^{i, j} > 0$), le temps de trajet $c_k^{i,j}$ est une constante par rapport à $k$. En effet, si ce n'était pas le cas, des voyageurs auraient intérêt à quitter un chemin plus lent pour un plus rapide, et cela maintiendrait les autres contraintes. En d'autres termes, il existe des réels positifs $(u_{i, j})$ tels que
\begin{align*}
\forall (i, j) \in S^2, \forall k \in P_{i, j}, f_{k}^{i, j}(c_k^{i, j} - u_{i, j}) &= 0 \\
\forall (i, j) \in S^2, \forall k \in P_{i, j}, c_k^{i, j} - u_{i, j} &>= 0\\
\forall (i, j) \in S^2, \sum_{k \in P_{i, j}}f_{k}^{i, j} &= q_{i, j}  \\
\forall (i, j) \in S^2, \forall k \in P_{i, j}, f_{k}^{i, j} &\geq 0
\end{align*}
Il s'avère que ce sont exactement les conditions de KKT du programme de minimisation suivant : 

\begin{align*}
&\min \sum_{a \in A} \int_0^{x_a}t_a(y)dy\\
\text{s.c.} \quad & \\
& \forall (i, j) \in S^2, q_{i, j} = \sum_{k \in P_{i, j}}f_{k}^{i, j} \\
& \forall (i, j) \in S^2, \forall k \in P_{i, j}, f_{k}^{i, j} \geq 0 \\
\end{align*}

Alors que la première fonction objectif avait une interprétation simple, celle du second est un pur artéfact mathématique.
Sous les hypothèses de croissance de $t_a$ et de convexité de $x \to xt_a(x)$ pour tout $a \in A$ (qui seront vérifiées par les fonctions que nous emploierons), ces deux programmes sont des problèmes de minimasation convexes et admettent donc une unique solution.

### 3) Résolution du modèle

Soient $k$ un entier naturel, $\mathcal{C}$ une partie compacte convexe de de $\mathbb{R}^k$ et $f : \mathcal{C} \to \mathbb{R}$ une fonction convexe différentiable. Nous cherchons à résoudre
\begin{align*}
\text{Minimiser} \quad &f(x) \\
\text{sous contrainte} \quad &x \in \mathcal{C}
\end{align*}
L'algorithme de Franke-Wolfe est le suivant :

**Initialisation** : on choisit un point $x_0$ de $\mathcal{C}$ quelconque et on pose $n \leftarrow 0$.
1.  On cherche $s_n$ minimisant $s \nabla f(x_n)^\text{T}$ sous contrainte $s \in \mathcal{C}$ (on minimise l'approximation affine de $f$ au voisinnage de $x_n$, ce qui donne la direction de descente) 
2. On cherche $\alpha_n$ minimisant $f(x_n + \alpha(s_n - x_n))$ (on minimise $f$ le long du segement $[x_n, s_n]$ pour obtenir le pas de descente)
3. On pose $x_{n+1} = x_n + \alpha(s_n - x_n)$, $n \leftarrow n + 1$ et on revient à l'étape 1.

Soit $x^{*}$ un minimiseur de $f$. Alors $f(x_n) \to f(x^{*})$.
Dans le cas de l'équilibre utilisateur, l'étape 1. à l'itération $n$ est 
\begin{align*}
\text{minimiser} \quad & \sum_{a \in A} t^n_ay_a \\
\text{sous les contraintes} \quad &\\
& \forall (i, j) \in S^2, q_{i, j} = \sum_{k \in P_{i, j}}g_{k}^{i, j} \\
& \forall (i, j) \in S^2, \forall k \in P_{i, j}, g_{k}^{i, j} \geq 0 \\
\end{align*}
où l'on a posé $ \forall a \in A, y_a = \sum_{(i, j) \in S^2}\sum_{k \in P_{i, j}} g_{k}^{i, j} \delta_{i, j}^{a, k}$ et $t_a^n = t_a(x_a^n)$. Dans ce programme, $y_a$ est la variable représentant le flux sur l'arête $a$ et $g_{k}^{i, j}$ le flux pour le chemin $k$ connectant le couple O-D $(i, j)$. En d'autres termes, ce programme demande de minimiser le temps de trajet total sur un réseau de transport où les temps de trajets sont fixes. Cela se fait en assignant chaque voyageur au chemin le plus rapide connectant son origine à sa destination. Le problème du plus court chemin dans un graphe est un problème algorithmique classique, que l'on peut résoudre avec l'algorithme de Djikstra.
Dans le cas de l'optimum système, la fonction objectif est remplacée par $\sum_{a \in A} y_a(x_a^n t^n_a + \dot{t}^n_a)$, ce qui conduit à un problème très similaire.
La force de l'algorithme de FW est donc de ramener un problème d'optimisation multidimensionnel au problème des plus courts chemins et la minimisation d'une fonction à variable réelle, deux problèmes bien plus simples.

## 4) Implémentation

In [ ]:
!pip install numpy scipy networkx

In [6]:
import numpy as np
import networkx as nx
import scipy
import collections
import warnings

warnings.filterwarnings("ignore")

UE = 0
SO = 1

Function = collections.namedtuple("Function", ["antideriv", "main", "deriv"])

def get_linear_function(a: float, b: float):
    def antideriv(x):
        return a*x**2 / 2 + b * x
    
    def main(x):
        return a*x + b

    def deriv(x):
        return a

    return  Function(antideriv, main, deriv)

null_function = get_linear_function(0, 0)

class NetworkGraph:

    def __init__(self, graph, od_demand, cost_functions):
        self.graph = graph
        self.od_demand = od_demand
        self.cost_functions = cost_functions
        self.order = graph.order()

    def solve(self, mode, max_steps = 20):
        if mode == UE:
            t = {edge: self.cost_functions[edge].main(0) for edge in G.edges}
            shortest_path = dict(nx.shortest_path(self.graph, weight = lambda i, j, data: t.get((i, j), 0)))
            x = np.zeros((self.order, self.order))
            for i in shortest_path:
                for j in shortest_path[i]:
                    path = shortest_path[i][j]
                    for k in range(len(path) - 1):
                        x[path[k]][path[k+1]] += self.od_demand[i, j]

            for k in range(max_steps):
                t = {edge: self.cost_functions[edge].main(x[*edge]) for edge in G.edges}
                shortest_path = dict(nx.shortest_path(self.graph, weight = lambda i, j, data: t.get((i, j), 0)))
                y = np.zeros((self.order, self.order))
                for i in shortest_path:
                    for j in shortest_path[i]:
                        path = shortest_path[i][j]
                        for k in range(len(path) - 1):
                            y[path[k]][path[k+1]] += self.od_demand[i, j]
    
                def f(alpha):
                    z = x + alpha * (y - x)
                    return sum(self.cost_functions[edge].antideriv(z[edge]) for edge in self.graph.edges)
    
                def f_p(alpha):
                    z = x + alpha * (y - x)
                    return sum((y[edge] - x[edge]) * self.cost_functions[edge].main(z[edge]) for edge in self.graph.edges)
    
                res = scipy.optimize.minimize_scalar(f, bounds = (0, 1))
                alpha = res.x
                x = x + alpha * (y - x)
            return x

# II. Application

Nous allons tester notre modèle sur un exemple simple, tiré de la page Wikipédia sur le paradoxe de Braess. Il peut être résolu manuellement et permettra de valider notre approche.
![img](https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Braess_paradox_road_example.svg/1920px-Braess_paradox_road_example.svg.png)
Considérons le réseau décrit dans le diagramme ci-contre, sur lequel 4 000 conducteurs souhaitent passer du point Start au point End. Sur la voie Start-A et la voie B-End, le temps de trajet est égal au nombre de voyageurs (T) divisé par 100, et sur la voie Start-B et la voie A-End, il est constant à 45 minutes. Si la voie en pointillé n'existe pas (le réseau possède alors 4 voies), le temps pour effectuer Start-A-End avec ${\displaystyle a}$ véhicules devrait être  ${\displaystyle {\dfrac {a}{100}}+45}$. Et le temps pour effectuer Start-B-End avec ${\displaystyle b}$ véhicules devrait être  ${\displaystyle {\dfrac {b}{100}}+45}$. Si l'une des routes était plus courte, ce ne serait pas un équilibre de Nash : un conducteur rationnel opterait pour la route la plus courte. Comme il y a 4 000 conducteurs, le fait que  ${\displaystyle a+b=4000}$ peut être utilisé pour en déduire que ${\displaystyle a=b=2000}$ quand le système est à l'équilibre. Par conséquent, chaque trajet dure ${\displaystyle {\dfrac {2000}{100}}+45=65}$ minutes.

In [7]:
G = nx.Graph()
start = 0
a = 1
b = 2
end = 3
G.add_edges_from([(start, a), (start, b), (a, end), (b, end)])
od_demand = np.zeros((4, 4))
od_demand[start, end] = 4000
cost_functions = {
    (start, a) : get_linear_function(1/100, 0),
    (start, b) : get_linear_function(0, 45),
    (a, end) : get_linear_function(0, 45),
    (b, end) : get_linear_function(1/100, 0)
                 }

network_graph = NetworkGraph(G, od_demand, cost_functions)
print(network_graph.solve(UE))

[[   0.         2000.01122029 1999.98877971    0.        ]
 [   0.            0.            0.         2000.01122029]
 [   0.            0.            0.         1999.98877971]
 [   0.            0.            0.            0.        ]]


Maintenant, ajoutons l'axe représenté par la ligne en pointillé, avec un temps de parcours tellement court qu'il en est négligeable, c'est-à-dire qu'il compte 0. Dans cette situation, tous les conducteurs vont choisir Start-A plutôt que Start-B, car Start-A prendra seulement ${\displaystyle {\dfrac {T}{100}}={\dfrac {4000}{100}}=40}$ minutes au pire, alors que Start-B prendra à coup sûr 45 minutes. Une fois au point A, tout conducteur rationnel choisira la route « gratuite » vers B, et de là continuera vers End, car là encore, A-End prendra à coup sûr 45 minutes alors que A-B-End prendra au plus ${\displaystyle 0+{\dfrac {4000}{100}}=40}$ minutes. Le temps de trajet de chaque conducteur est donc de ${\displaystyle {\dfrac {4000}{100}}+{\dfrac {4000}{100}}=80}$ minutes, un temps supérieur aux 65 minutes requises si la ligne rapide A-B n'existait pas. Aucun conducteur n'a intérêt à changer, car les deux routes initiales (Start-A-End et Start-B-End) prennent maintenant toutes les deux 85 minutes. Si tous les conducteurs se mettaient d'accord pour ne pas utiliser la liaison A-B, chacun en bénéficierait, par une réduction de son trajet de 15 minutes. Toutefois, parce qu'un conducteur individuel aura toujours intérêt à prendre la voie A-B, la distribution socialement optimale n'est pas stable, et le paradoxe de Braess se produit. 

In [8]:
G.add_edge(a, b)
cost_functions[(a, b)] = null_function
network_graph = NetworkGraph(G, od_demand, cost_functions)
print(network_graph.solve(UE))

[[   0. 4000.    0.    0.]
 [   0.    0. 4000.    0.]
 [   0.    0.    0. 4000.]
 [   0.    0.    0.    0.]]


Le modèle fonctionne donc correctement sur cet exemple.

# IV. Références

- Paradoxe de Braess. (2024, octobre 3). *Wikipédia, l'encyclopédie libre.* Page consultée le 07:40, octobre 3, 2024 à partir de http://fr.wikipedia.org/w/index.php?title=Paradoxe_de_Braess&oldid=219124217.
- Sheffi, Yossi. (1984). Urban Transportation Networks: Equilibrium Analysis With Mathematical Programming Methods. https://www.researchgate.net/publication/230663831_Urban_Transportation_Networks_Equilibrium_Analysis_With_Mathematical_Programming_Methods